version: 2.1

# Parameters passed from setup workflow on config.yml
parameters:
  commit_message:
    type: string
    default: ""

jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - run:
          command: echo "commit message << pipeline.parameters.commit_message >>"
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample:
    when:
      and:
        - matches:
            pattern: "^release.+"
            value: << pipeline.git.branch >>
        - matches:
            pattern: "^(?:(?!NOCIRCLECI).)*$"
            value: << pipeline.parameters.commit_message >>
    jobs:
      - build
