version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1

jobs:
  setup:
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/go
      - image: cimg/go:1.21

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          command: |
            export COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            echo "{\"commit_message\": \"$COMMIT_MESSAGE\"}" >> set-up-params.json
      - continuation/continue:
          parameters: set-up-params.json
          configuration_path: .circleci/build.yml

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  setup:
    jobs:
      - setup
